# Generated by Django 4.2.6 on 2023-11-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist_id',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist_name',
            field=models.ManyToManyField(to='zing_it.playlist'),
        ),
    ]
