# Generated by Django 4.2.6 on 2023-11-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0002_remove_song_playlist_id_song_playlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist_name',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
