# Generated by Django 4.2.6 on 2023-11-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0003_remove_song_playlist_name_song_playlist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
