# Generated by Django 4.2.6 on 2023-11-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0004_alter_song_artist_alter_song_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.CharField(max_length=255),
        ),
    ]
