# Generated by Django 4.2.6 on 2023-11-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0005_alter_song_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
