# Generated by Django 4.2.6 on 2023-11-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0008_alter_song_playlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlist_id',
            field=models.IntegerField(default=0),
        ),
    ]
